### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by sklart** [GrzybDev/KingdomHeartsTool#1]
Thanks for the useful utility!
After run
`python -m khtool -v -u "c:\Games\Kingdom Hearts HD 1.5 + 2.5 ReMIX\Image\en\*.hed" -o output\en`
it gives the following error
```
Archive: c:\Games\Kingdom Hearts HD 1.5 + 2.5 ReMIX\Image\en\bbs_first
Reading archive header file c:\Games\Kingdom Hearts HD 1.5 + 2.5 ReMIX\Image\en\bbs_first.hed...
Files in archive: 822
Extracting archive c:\Games\Kingdom Hearts HD 1.5 + 2.5 ReMIX\Image\en\bbs_first.pkg...
Extracting file 674F96F89215E8FECBC9AAE50E16D07F...
Reading file data... (Offset: 0x0, Size: 128 bytes)
Generating encryption key...
Decrypting file...
Decompressing file...
Matched file extension: .edp
Now saving file to: output\en/bbs_first/674F96F89215E8FECBC9AAE50E16D07F.edp...
Extracting file 1A294CE5D2C6A77263D82D3BF9E5DE8D...
Reading file data... (Offset: 0x90, Size: 4080 bytes)
Generating encryption key...
Decrypting file...
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "f:\Games\Kingdom Hearts HD 1.5 + 2.5 ReMIX [FitGirl Repack]\KingdomHeartsTool-main\khtool\__main__.py", line 99, in <module>
    main()
  File "f:\Games\Kingdom Hearts HD 1.5 + 2.5 ReMIX [FitGirl Repack]\KingdomHeartsTool-main\khtool\__main__.py", line 62, in main
    func(in_path, out_path, is_verbose)
  File "f:\Games\Kingdom Hearts HD 1.5 + 2.5 ReMIX [FitGirl Repack]\KingdomHeartsTool-main\khtool\unpack.py", line 35, in __init__
    self.extract_package(self.archive_path + ".pkg")
  File "f:\Games\Kingdom Hearts HD 1.5 + 2.5 ReMIX [FitGirl Repack]\KingdomHeartsTool-main\khtool\unpack.py", line 95, in extract_package
    file_data = self.__read_file(pkg_file, size, entry, decrypt, decompress)
  File "f:\Games\Kingdom Hearts HD 1.5 + 2.5 ReMIX [FitGirl Repack]\KingdomHeartsTool-main\khtool\unpack.py", line 139, in __read_file
    data = Encryption.get_chunk(key, data, i, 0xA)
  File "f:\Games\Kingdom Hearts HD 1.5 + 2.5 ReMIX [FitGirl Repack]\KingdomHeartsTool-main\khtool\encryption.py", line 56, in get_chunk
    array[num] ^= key[j + 0x10 * i]
IndexError: list index out of range
```
In output\en\bbs_first\ there is only one file **674F96F89215E8FECBC9AAE50E16D07F.edp**

**Comment by GrzybDev** [comment]
Hi!

It seems that your archive is modified in some way, i just extracted all game archives (from **legit** version) without any problem.
Are you sure that this archive is not corrupted or tampered?

**Comment by GrzybDev** [comment]
I have commited "fix" which should at least make my tool do not crash if decryption fails for some reason.
It should allow you to unpack files "as-is" if decryption fails, can you check it? #2

**Comment by sklart** [comment]
I will try to rehash the content of the game tomorrow.

Now I'm attaching a log with fix 
`Archive: c:\Games\Kingdom Hearts HD 1.5 + 2.5 ReMIX\Image\en\bbs_first
Reading archive header file c:\Games\Kingdom Hearts HD 1.5 + 2.5 ReMIX\Image\en\bbs_first.hed...
Files in archive: 822
Extracting archive c:\Games\Kingdom Hearts HD 1.5 + 2.5 ReMIX\Image\en\bbs_first.pkg...
Extracting file 674F96F89215E8FECBC9AAE50E16D07F...
Reading file data... (Offset: 0x0, Size: 128 bytes)
Generating encryption key...
Decrypting file...
Decompressing file...
Matched file extension: .edp
Now saving file to: output\en/bbs_first/674F96F89215E8FECBC9AAE50E16D07F.edp...
Extracting file 1A294CE5D2C6A77263D82D3BF9E5DE8D...
Reading file data... (Offset: 0x90, Size: 4080 bytes)
Generating encryption key...
Decrypting file...
Cannot decrypt file! (Skipping decompression if necessary, this file may be garbled)
Extracting sub-archive 1A294CE5D2C6A77263D82D3BF9E5DE8D...
Reading archive data...
Reading file from sub-archive 1A294CE5D2C6A77263D82D3BF9E5DE8D... (-0.dds, 35440 bytes)
Generating encryption key...
Decrypting file...
Cannot decrypt file! (Skipping decompression if necessary, this file may be garbled)
Now extracting file from archive to: output\en/bbs_first/1A294CE5D2C6A77263D82D3BF9E5DE8D/-0.dds...
Saving sub-archive header data...
Matched file extension: .dat
Now saving file to: output\en/bbs_first/1A294CE5D2C6A77263D82D3BF9E5DE8D.dat...
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "f:\Games\Kingdom Hearts HD 1.5 + 2.5 ReMIX [FitGirl Repack]\KingdomHeartsTool-main\khtool\__main__.py", line 99, in <module>
    main()
  File "f:\Games\Kingdom Hearts HD 1.5 + 2.5 ReMIX [FitGirl Repack]\KingdomHeartsTool-main\khtool\__main__.py", line 62, in main
    func(in_path, out_path, is_verbose)
  File "f:\Games\Kingdom Hearts HD 1.5 + 2.5 ReMIX [FitGirl Repack]\KingdomHeartsTool-main\khtool\unpack.py", line 35, in __init__
    self.extract_package(self.archive_path + ".pkg")
  File "f:\Games\Kingdom Hearts HD 1.5 + 2.5 ReMIX [FitGirl Repack]\KingdomHeartsTool-main\khtool\unpack.py", line 88, in extract_package
    entry = self.__get_file_meta_data(pkg_file, entryID)
  File "f:\Games\Kingdom Hearts HD 1.5 + 2.5 ReMIX [FitGirl Repack]\KingdomHeartsTool-main\khtool\unpack.py", line 224, in __get_file_meta_data
    file_size, subentries_count, compressed_file_size, file_info, = struct.unpack("iiii", pkg_file.read(16))
struct.error: unpack requires a buffer of 16 bytes`


Folder contents KingdomHeartsTool-main\output\en\bbs_first
18.04.2021  22:25    <DIR>          .
18.04.2021  22:25    <DIR>          ..
18.04.2021  22:25    <DIR>          1A294CE5D2C6A77263D82D3BF9E5DE8D
18.04.2021  22:25        48            1A294CE5D2C6A77263D82D3BF9E5DE8D.dat
18.04.2021  22:25        336           674F96F89215E8FECBC9AAE50E16D07F.edp
               2 files            384 bytes

Folder contents KingdomHeartsTool-main\output\en\bbs_first\1A294CE5D2C6A77263D82D3BF9E5DE8D

18.04.2021  22:25    <DIR>          .
18.04.2021  22:25    <DIR>          ..
18.04.2021  22:25         0         -0.dds
18.04.2021  22:25       104       entries.json
               2  files          104 bytes

**Comment by sklart** [comment]
It seems that pkg-files are corrupted. I see a significant difference in their size between my local versions and downloading versions. After downloading and rehashing I will try  your tool again.
Thanks for help and sorry for false alarm.
